package com.globant.example.mentorapp.home.presentation.model;

import java.util.List;

/**
 * Represents the model necessary for the ui understand the events generated by the presenter.
 * Created by oscar.amezquita on 16/06/2017.
 */

public class ListUsersViewModel {

    final List<ModelUserEntity> users;
    final errorResponse error;
    final Boolean progress;

    public ListUsersViewModel(List<ModelUserEntity> users, errorResponse error, Boolean progress) {
        this.users = users;
        this.error = error;
        this.progress = progress;
    }

    public List<ModelUserEntity> getUsers() {
        return users;
    }

    public errorResponse getError() {
        return error;
    }

    public Boolean getProgress() {
        return progress;
    }

    public enum errorResponse {

        ERROR_RESPONSE, ERROR_CONNECTION

    }
}
