package com.globant.example.mentorapp.home.presentation.model;

import com.globant.example.mentorapp.mvp.base.BaseModel;

import java.util.List;

/**
 * Represents the model necessary for the ui understand the events generated by the presenter.
 * Created by oscar.amezquita on 16/06/2017.
 */

public class ListUsersViewModel extends BaseModel {

    private final List<ModelUserEntity> users;
    private final ErrorResponse error;
    private final boolean progress;

    public ListUsersViewModel(List<ModelUserEntity> users, ErrorResponse error, boolean progress) {
        this.users = users;
        this.error = error;
        this.progress = progress;
    }

    public List<ModelUserEntity> getUsers() {
        return users;
    }

    public ErrorResponse getError() {
        return error;
    }

    public boolean getProgress() {
        return progress;
    }

}
