package com.globant.example.mentorapp.subscriberDetails.presentation.model;

import com.globant.example.mentorapp.mvp.base.BaseModel;

import java.util.List;

/**
 * Represents the model necessary for the users detail ui understand the events generated by the presenter.
 * Created by oscar.amezquita on 17/07/2017.
 */

public class UserDetailsViewModel extends BaseModel {

    private final DetailsModel userDetails;
    private final List<RepositoryModel> userRepos;
    private final ErrorResponse error;
    private final boolean progress;

    public UserDetailsViewModel(DetailsModel user, List<RepositoryModel> modelListRepos, ErrorResponse error, boolean progress) {
        this.userDetails = user;
        this.userRepos = modelListRepos;
        this.error = error;
        this.progress = progress;
    }

    public DetailsModel getUserDetails() {
        return userDetails;
    }

    public ErrorResponse getError() {
        return error;
    }

    public boolean getProgress() {
        return progress;
    }

    public List<RepositoryModel> getUserRepos() {
        return userRepos;
    }
}
